spring:
  profiles:
    include: oauth,real-db
  session:
    store-type: jdbc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mustache:
    enabled: true
    prefix: classpath:/template/
    suffix: .mustache
  mvc:
    view:
      prefix: classpath:/template/
      suffix: .mustache
