spring:
  profiles:
    include: oauth, real-db
  session:
    store-type: jdbc
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  h2:
    console:
      enabled: true
  devtools:
    restart:
      quiet-period: 1ms
      poll-interval: 1s
logging:
  level:
    com.web.board.book: debug
