spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true
#    open-in-view: false
  h2:
    console:
      enabled: true
  mustache:
    enabled: true
    prefix: classpath:/template/
    suffix: .mustache
  mvc:
    view:
      prefix: classpath:/template/
      suffix: .mustache
